@startuml Dependency_AB
' Image can be obtained from
' https://www.plantuml.com/plantuml/uml/SyfFKj2rKt3CoKnELR1Io4ZDoSa70000

' Write all modules here
object ABA {
    * aba
}

object ABB {
    * abb
}

' Write all dependencies here
' X --> Y means X depends on Y
ABB --> ABA : abba uses abaa

@enduml