@startuml Dependency_Data
' Image can be obtained from
' https://www.plantuml.com/plantuml/uml/SyfFKj2rKt3CoKnELR1Io4ZDoSa70000

' Write all modules here
object AB_DataA {
    * data
    * data
}

object AB_DataB {
    * data
    * data
}

object Vector {
    * Vector(Basic)
    * Vector2D
}

' Write all dependencies here
' X --> Y means X depends on Y
AB_DataA <-- AB_DataB

@enduml